import { test } from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import ts from 'typescript'
function load(file, imports = {}) { const code = ts.transpileModule(fs.readFileSync(file, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText; const exports = {}; new Function('require', 'exports', code)(name => { if (!(name in imports)) throw Error(`Unexpected import ${name}`); return imports[name] }, exports); return exports }
const validation = load('src/features/deals/validation.ts')
const workspace = '11111111-1111-1111-1111-111111111111', dealId = '22222222-2222-2222-2222-222222222222', pipelineId = '33333333-3333-3333-3333-333333333333', stageId = '44444444-4444-4444-4444-444444444444', contactId = '55555555-5555-5555-5555-555555555555', companyId = '66666666-6666-6666-6666-666666666666'
const deal = { id: dealId, name: 'Large renewal', amount: '1250.50', currency: 'USD', pipeline_id: pipelineId, stage_id: stageId, contact_id: contactId, company_id: companyId, expected_close_date: '2026-10-01', created_at: '2026-01-01', updated_at: '2026-01-01' }
function service(permissions = ['DEALS_VIEW'], results = []) { const calls = []; let index = 0; const context = { workspaceId: workspace, permissions: new Set(permissions), supabase: { from(table) { calls.push(['from', table]); const result = results[index++] || { data: [], count: 0, error: null }; const chain = { then: resolve => Promise.resolve(result).then(resolve) }; for (const method of ['select','eq','in','order','range','or','maybeSingle','insert','update','limit']) chain[method] = (...args) => { calls.push([method, ...args]); return chain }; return chain } } }; const api = load('src/server/deals.ts', { 'server-only': {}, 'next/navigation': { notFound: () => { throw Error('NOT_FOUND') } }, '@/server/app-context': { getAppContext: async () => context }, '@/features/deals/validation': validation }); return { ...api, calls } }
function form(amount = '1250.50') { const value = new FormData(); value.set('name', ' Large renewal '); value.set('amount', amount); value.set('pipeline_id', pipelineId); value.set('stage_id', stageId); value.set('contact_id', contactId); value.set('company_id', companyId); value.set('expected_close_date', '2026-10-01'); return value }

test('DEALS_VIEW is required before list/detail/edit reads, including manage-only', async () => { for (const p of [[], ['DEALS_MANAGE']]) { const s = service(p); await assert.rejects(s.getDeals(1), /NOT_FOUND/); await assert.rejects(s.getDealById(dealId), /NOT_FOUND/); await assert.rejects(s.getDealForEdit(dealId), /NOT_FOUND/); assert.equal(s.calls.length, 0) } })
test('list is workspace scoped, safely searched and stably paginated by 50', async () => { const s = service(['DEALS_VIEW'], [{ data: [deal], count: 70, error: null }]); const data = await s.getDeals(2, ' renewal%_ '); assert.equal(data.total, 70); assert.equal(data.deals[0].name, deal.name); assert.ok(s.calls.some(c => c[0] === 'eq' && c[1] === 'workspace_id' && c[2] === workspace)); assert.ok(s.calls.some(c => c[0] === 'range' && c[1] === 50 && c[2] === 99)); assert.ok(s.calls.some(c => c[0] === 'order' && c[1] === 'created_at')); assert.ok(s.calls.some(c => c[0] === 'order' && c[1] === 'id')); assert.ok(s.calls.some(c => c[0] === 'or' && c[1].includes('\\%') && c[1].includes('\\_'))) })
test('related data is never queried without its own read permission', async () => { const s = service(['DEALS_VIEW'], [{ data: deal, error: null }]); const data = await s.getDealById(dealId); assert.equal(data.deal.contact_name, null); assert.equal(data.deal.company_name, null); assert.equal(data.deal.pipeline_name, null); assert.deepEqual(s.calls.filter(c => c[0] === 'from'), [['from','deals']]) })
test('foreign, missing and malformed deal IDs share unavailable behavior', async () => { for (const id of [dealId, '77777777-7777-7777-7777-777777777777']) await assert.rejects(service(undefined, [{ data: null, error: null }]).getDealById(id), /NOT_FOUND/); const s = service(); await assert.rejects(s.getDealById('bad'), /NOT_FOUND/); assert.equal(s.calls.length, 0) })
test('manage-only create uses server workspace/currency and ignores protected fields and hidden relations', async () => { const value = form(); for (const key of ['id','workspace_id','owner_user_id','created_at','updated_at','won_at','lost_at','source_id']) value.set(key, 'forged'); const s = service(['DEALS_MANAGE','PIPELINES_VIEW'], [{ data: { id: pipelineId }, error: null }, { data: { id: stageId }, error: null }, { data: { currency: 'VND' }, error: null }, { error: null }]); const result = await s.createDeal(value); assert.deepEqual(result, { success: true }); const payload = s.calls.find(c => c[0] === 'insert')[1]; assert.equal(payload.workspace_id, workspace); assert.equal(payload.currency, 'VND'); assert.equal(payload.contact_id, null); assert.equal(payload.company_id, null); for (const key of ['id','owner_user_id','created_at','won_at','source_id']) assert.ok(!(key in payload)) })
test('create/edit require manage and edit also requires view', async () => { for (const p of [[], ['DEALS_VIEW'], ['DEALS_MANAGE']]) { const s = service(p); if (!p.includes('DEALS_MANAGE')) await assert.rejects(s.createDeal(form()), /NOT_FOUND/); await assert.rejects(s.updateDeal(dealId, form()), /NOT_FOUND/) } })
test('pipeline, stage, contact and company are verified in the active workspace', async () => { const p = ['DEALS_VIEW','DEALS_MANAGE','PIPELINES_VIEW','CONTACTS_VIEW','COMPANIES_VIEW']; const badPipeline = service(p, [{ data: null, error: null }, { data: null, error: null }]); assert.equal((await badPipeline.createDeal(form())).fields.pipeline_id, 'Select an available pipeline.'); assert.ok(!badPipeline.calls.some(c => c[0] === 'insert')); const mismatch = service(p, [{ data: { id: pipelineId }, error: null }, { data: null, error: null }]); assert.equal((await mismatch.createDeal(form())).fields.stage_id, 'Select a stage from the selected pipeline.'); const badContact = service(p, [{ data: { id: pipelineId }, error: null }, { data: { id: stageId }, error: null }, { data: null, error: null }]); assert.equal((await badContact.createDeal(form())).fields.contact_id, 'Select an available contact.') })
test('monetary validation rejects negatives, exponent, NaN and Infinity', async () => { for (const amount of ['-1','1e3','NaN','Infinity','']) { const s = service(['DEALS_MANAGE','PIPELINES_VIEW']); const result = await s.createDeal(form(amount)); assert.equal(result.fields.amount, 'Enter a non-negative decimal value.'); assert.ok(!s.calls.some(c => c[0] === 'insert')) } })
test('deal form prevents immediate duplicate submission and shows pending state', () => { const source = fs.readFileSync('src/components/deals/deal-form.tsx','utf8'); assert.match(source,/useRef\(false\)/); assert.match(source,/submitting\.current \|\| pending/); assert.match(source,/Saving\.\.\./) })
test('deal navigation is permission based', () => { const { filterNavigation } = load('src/components/app-shell/navigation.ts'); assert.ok(filterNavigation(new Set(['DEALS_VIEW'])).mainItems.some(item => item.href === '/app/deals')); assert.ok(!filterNavigation(new Set(['DEALS_MANAGE'])).mainItems.some(item => item.href === '/app/deals')) })
